### Получение токена (JWT)
POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
  "email": "somemail@mail.ru",
  "password": "qweDSA123"
}

###

### Получение информации о текущем пользователе
GET http://127.0.0.1:8000/auth/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NDU2MzE0LCJqdGkiOiJmN2Q1OWQ2MzVmYzU0ODQ5OTQ0ZTNjZGUwYWI2YmU2OCIsInVzZXJfaWQiOjE3fQ.f6of2PwDOUNfsfB4MzyJpvA8ZUIatyf2whip9bvD2dc

###

### Создание компании (только для SUPERUSER)
POST http://127.0.0.1:8000/api/companies/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Test Company"
}

###

### Получение списка компаний (только для SUPERUSER)
GET http://127.0.0.1:8000/api/companies/
Authorization: Bearer {{access_token}}

###

### Создание пользователя (MANAGER или EMPLOYEE)
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "manager@test.com",
  "password": "strongpassword123",
  "first_name": "Anna",
  "last_name": "Ivanova",
  "role": "MANAGER"
}

###

### Получение всех пользователей своей компании (для менеджера)
GET http://127.0.0.1:8000/api/users/
Authorization: Bearer {{access_token}}

###

### Получение контроллеров
GET http://127.0.0.1:8000/api/controllers/
Authorization: Bearer {{access_token}}


###

PATCH /api/controllers/<controller_id>/
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "control_mode": "auto"
}

###

### Получение сообщений от датчика
GET http://127.0.0.1:8000/api/messages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzUzMjU2LCJqdGkiOiI3ZTM1YjkyZThmNTQ0OTMyYjEwYmIxZTJiZWY0ODNiZiIsInVzZXJfaWQiOjE3fQ.puFvIlM9NnZPhGk9YaW_8lr7NJJCW0-GrS0EZybzsO0


###

### сообщения по дате и сенсору 

GET http://127.0.0.1:8000/api/messages/?sensor=fc5c1a5e-ba02-4733-a62c-2c2b3d1534d4&start=2025-05-26T13:32:00Z&end=2025-05-26T13:39:00Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzUzMjU2LCJqdGkiOiI3ZTM1YjkyZThmNTQ0OTMyYjEwYmIxZTJiZWY0ODNiZiIsInVzZXJfaWQiOjE3fQ.puFvIlM9NnZPhGk9YaW_8lr7NJJCW0-GrS0EZybzsO0
Content-Type: application/json

###

GET http://127.0.0.1:8000/messages/latest/?sensor=fc5c1a5e-ba02-4733-a62c-2c2b3d1534d4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzUzMjU2LCJqdGkiOiI3ZTM1YjkyZThmNTQ0OTMyYjEwYmIxZTJiZWY0ODNiZiIsInVzZXJfaWQiOjE3fQ.puFvIlM9NnZPhGk9YaW_8lr7NJJCW0-GrS0EZybzsO0
Content-Type: application/json


###

### Получение всех контроллеров
GET http://127.0.0.1:8000/api/controllers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzUzMjU2LCJqdGkiOiI3ZTM1YjkyZThmNTQ0OTMyYjEwYmIxZTJiZWY0ODNiZiIsInVzZXJfaWQiOjE3fQ.puFvIlM9NnZPhGk9YaW_8lr7NJJCW0-GrS0EZybzsO0

###



###

### Получение всех датчиков
GET http://127.0.0.1:8000/api/sensors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzUzMjU2LCJqdGkiOiI3ZTM1YjkyZThmNTQ0OTMyYjEwYmIxZTJiZWY0ODNiZiIsInVzZXJfaWQiOjE3fQ.puFvIlM9NnZPhGk9YaW_8lr7NJJCW0-GrS0EZybzsO0

###

### Получение всех реле
GET http://127.0.0.1:8000/api/relays/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzUzMjU2LCJqdGkiOiI3ZTM1YjkyZThmNTQ0OTMyYjEwYmIxZTJiZWY0ODNiZiIsInVzZXJfaWQiOjE3fQ.puFvIlM9NnZPhGk9YaW_8lr7NJJCW0-GrS0EZybzsO0




###


### Отправка сообщения от контроллера (через отдельную аутентификацию, см. ниже)
POST http://127.0.0.1:8000/api/messages/
Content-Type: application/json
x-api-key: <API_KEY_КОНТРОЛЛЕРА>

{
  "sensor": 1,
  "value": 24.7,
  "status": "ok"
}

###


POST http://127.0.0.1:8000/control/63f9b53c-33a8-486d-b71f-53eb526e4ce9/relay/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzU5MjY0LCJqdGkiOiI1ODEzNTQ2YmM4OTU0MjdkYjAzOWRiMWU2Y2JmZjlmNCIsInVzZXJfaWQiOjE3fQ.j77BKrd6X0S_3bFGEMlXuYlwsebxtcC969-WA_AlQaI

{
  "relay_uuid": "ec4956f1-1079-47f2-9e0b-460cb4798c9c",
  "is_working": true
}

###


###
