version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto4
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
