# Generated by Django 4.2.21 on 2025-05-20 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='control_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sensor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ManualControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controller')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
