# Generated by Django 4.2.21 on 2025-05-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_controller_control_mode_controller_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='uuid',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
