# Generated by Django 4.2.21 on 2025-05-20 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_controller_uuid_alter_sensor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
