# Generated by Django 4.2.21 on 2025-05-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_controller_uuid_alter_sensor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manualcontrollog',
            name='action',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manualcontrollog',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_logs', to='api.controller'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.controller'),
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('pump', 'Pump'), ('light', 'Light'), ('fan', 'Fan')], max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='api.controller')),
            ],
            options={
                'unique_together': {('controller', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='manualcontrollog',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.relay'),
        ),
    ]
