# Generated by Django 4.2.21 on 2025-05-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_controller_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relay',
            old_name='state',
            new_name='is_working',
        ),
    ]
