# Generated by Django 4.2.21 on 2025-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_state_relay_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
