# Generated by Django 4.2.21 on 2025-05-21 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_relay_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
