# Generated by Django 4.2.21 on 2025-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sensor_critical_max_sensor_critical_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unit_of_measurements',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TelegramChat',
        ),
    ]
